title: Nurun 'Ala Nurin
author: non
email: ruswien.nona.amine-2015@ff.unair.ac.id
description: > # this means to ignore newlines until "baseurl:"
  Deep talk - Creative [Mind]-blowing

# social links
twitter_username: ruswien # DO NOT include the @ character, or else the build will fail!
github_username:  ruswiennona # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
